import catWithOrdinalCountEn from './client/en/catWithOrdinalCount'
import appleWithCountEn from './client/en/appleWithCount'
import catWithOrdinalCountDe from './client/de/catWithOrdinalCount'
import appleWithCountDe from './client/de/appleWithCount'
// This file is auto-generated by generate-locale.ts

export const interpolateTemplate = (text: string, data: Record<string, string>): string => {
    let theText = text
  
    theText = theText.replace(/{{\s*(\w+)\s*}}/g, (match, key) => {
      return key in data ? data[key] : match
    })
  
    return theText
  }
export type SupportedLanguage = 'de' | 'en';
  export const defaultLanguage: SupportedLanguage = 'en';
  
const deHello = "Hallo Welt!"
const deGreeting = "Hallo {name}!"
const deHome = "Startseite"
const enHello = "Hello world!"
const enGreeting = "Hello {name}!"
const enHome = "Home"
export const hello = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deHello;
case 'en': return enHello;
        default:
            return enHello
        }
    }
export const greeting = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deGreeting;
case 'en': return enGreeting;
        default:
            return enGreeting
        }
    }
export const home = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deHome;
case 'en': return enHome;
        default:
            return enHome
        }
    }

    export function appleWithCount(lang: SupportedLanguage, count: number) {
      let text = "";
  
      switch (lang) {
         case "de": text = appleWithCountDe(count); break;
case "en": text = appleWithCountEn(count); break;
          default:
            break;
      }

      return interpolateTemplate(text, { count: `${count}` });
  }
    

    export function catWithOrdinalCount(lang: SupportedLanguage, count: number) {
      let text = "";
  
      switch (lang) {
         case "de": text = catWithOrdinalCountDe(count); break;
case "en": text = catWithOrdinalCountEn(count); break;
          default:
            break;
      }

      return interpolateTemplate(text, { count: `${count}` });
  }
    
export type StringKeys = 'hello' | 'greeting' | 'home' | 'appleWithCount' | 'catWithOrdinalCount'