// This file is auto-generated by generate-locale.ts

export const interpolateTemplate = (text: string, data: Record<string, string>): string => {
    let theText = text
  
    theText = theText.replace(/{{\s*(\w+)\s*}}/g, (match, key) => {
      return key in data ? data[key] : match
    })
  
    return theText
  }
export type SupportedLanguage = 'de' | 'en';
  export const defaultLanguage: SupportedLanguage = 'en';
  
const deAnotherFileHello = "Hallo Welt in anderes Datei!"
const deAnotherFileGreeting = "Hallo, anderes Datei {name}!"
const deAnotherFileHome = "Startseite anderes Datei"
const deAnotherFileClientHello = "Hallo Welt in einer anderen Client-Datei!"
const deAnotherFileClientAnotherBye = "auf Wiedersehen, {name}"
const deHello = "Hallo Welt!"
const deGreeting = "Hallo {name}!"
const deHome = "Startseite"
const deSomethingHello = "Hallo Welt in etwas!"
const deSomethingGreeting = "Hallo, etwas {name}!"
const deSomethingHome = "Startseite etwas"
const enAnotherFileHello = "Hello world in another file!"
const enAnotherFileGreeting = "Hello, another file {name}!"
const enAnotherFileHome = "Home another file"
const enAnotherFileClientHello = "Hello world in another client file!"
const enAnotherFileClientAnotherBye = "bye, {name}"
const enHello = "Hello world!"
const enGreeting = "Hello {name}!"
const enHome = "Home"
const enSomethingHello = "Hello world in something!"
const enSomethingGreeting = "Hello, something {name}!"
const enSomethingHome = "Home something"
export const anotherFileHello = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deAnotherFileHello;
case 'en': return enAnotherFileHello;
        default:
            return enAnotherFileHello
        }
    }
export const anotherFileGreeting = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deAnotherFileGreeting;
case 'en': return enAnotherFileGreeting;
        default:
            return enAnotherFileGreeting
        }
    }
export const anotherFileHome = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deAnotherFileHome;
case 'en': return enAnotherFileHome;
        default:
            return enAnotherFileHome
        }
    }
export const anotherFileClientHello = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deAnotherFileClientHello;
case 'en': return enAnotherFileClientHello;
        default:
            return enAnotherFileClientHello
        }
    }
export const anotherFileClientAnotherBye = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deAnotherFileClientAnotherBye;
case 'en': return enAnotherFileClientAnotherBye;
        default:
            return enAnotherFileClientAnotherBye
        }
    }
export const hello = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deHello;
case 'en': return enHello;
        default:
            return enHello
        }
    }
export const greeting = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deGreeting;
case 'en': return enGreeting;
        default:
            return enGreeting
        }
    }
export const home = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deHome;
case 'en': return enHome;
        default:
            return enHome
        }
    }
export const somethingHello = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deSomethingHello;
case 'en': return enSomethingHello;
        default:
            return enSomethingHello
        }
    }
export const somethingGreeting = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deSomethingGreeting;
case 'en': return enSomethingGreeting;
        default:
            return enSomethingGreeting
        }
    }
export const somethingHome = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deSomethingHome;
case 'en': return enSomethingHome;
        default:
            return enSomethingHome
        }
    }
export type StringKeys = 'anotherFileHello' | 'anotherFileGreeting' | 'anotherFileHome' | 'anotherFileClientHello' | 'anotherFileClientAnotherBye' | 'hello' | 'greeting' | 'home' | 'somethingHello' | 'somethingGreeting' | 'somethingHome'