// This file is auto-generated by generate-locale.ts

export const interpolateTemplate = (text: string, data: Record<string, string>): string => {
    let theText = text
  
    theText = theText.replace(/{{\s*(\w+)\s*}}/g, (match, key) => {
      return key in data ? data[key] : match
    })
  
    return theText
  }
export type SupportedLanguage = 'de' | 'en';
  export const defaultLanguage: SupportedLanguage = 'en';
  
const deHello = "Hallo Welt!"
const deGreeting = "Hallo {name}!"
const deHome = "Startseite"
const deSomethingHello = "Hallo Welt in etwas!"
const deSomethingGreeting = "Hallo, etwas {name}!"
const deSomethingHome = "Startseite etwas"
const enHello = "Hello world!"
const enGreeting = "Hello {name}!"
const enHome = "Home"
const enSomethingHello = "Hello world in something!"
const enSomethingGreeting = "Hello, something {name}!"
const enSomethingHome = "Home something"
export const hello = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deHello;
case 'en': return enHello;
        default:
            return enHello
        }
    }
export const greeting = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deGreeting;
case 'en': return enGreeting;
        default:
            return enGreeting
        }
    }
export const home = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deHome;
case 'en': return enHome;
        default:
            return enHome
        }
    }
export const somethingHello = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deSomethingHello;
case 'en': return enSomethingHello;
        default:
            return enSomethingHello
        }
    }
export const somethingGreeting = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deSomethingGreeting;
case 'en': return enSomethingGreeting;
        default:
            return enSomethingGreeting
        }
    }
export const somethingHome = (lang: SupportedLanguage) => {
      switch (lang) {
    case 'de': return deSomethingHome;
case 'en': return enSomethingHome;
        default:
            return enSomethingHome
        }
    }
export type StringKeys = 'hello' | 'greeting' | 'home' | 'somethingHello' | 'somethingGreeting' | 'somethingHome'